version: 2
updates:

  - package-ecosystem: "docker"
    directory: "a"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "b"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "c"
    schedule:
      interval: "daily"
